# Default config for dev

[object_store]
type = "local"
data_dir = "../seafowl-data"

[catalog]
type = "sqlite"
dsn = "../seafowl-data/seafowl.sqlite"

[frontend.postgres]
bind_port = 6432

[frontend.http]
bind_host = "0.0.0.0"

[frontend.flight]
bind_host = "0.0.0.0"
