[package]
name = "floc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.12"
tonic = "0.10"

[build-dependencies]
tonic-build = "0.10"
